# These are supported funding model platforms

github: sanamhub
patreon: sanampakuwal
open_collective: sanam
ko_fi: sanampakuwal
# tidelift: npm/@sanampakuwal%2Futils
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: sanam
issuehunt: sanamhub
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
